### ISSUE TITLE
next doesn't launch - sqlite

### ISSUE THREAD

**Issue by AlbertoEAF** [atlas-engineer/next#209]
Hello, 

I downloaded from github the project, changed the Make file to use as prefix my $home/.local (to avoid installing with sudo) and running next ends in this:

![Screenshot from 2019-05-12 09-02-01](https://user-images.githubusercontent.com/3976753/57579500-a55f9f80-7494-11e9-9eb5-25c734b19d35.png)

Where the code in the screenshot is this:
`(base) [2016]alberto.ferreira:/home/alberto.ferreira/code/external/next$ next
 <INFO> [08:59:45] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/alberto.ferreira/.config/next/init.lisp...
 <WARN> [08:59:45] next base.lisp (start) -
  swank:*communication-style* is set to :SPAWN, recommended value is :fd-handler
 <INFO> [08:59:45] next port.lisp (run-program port) -
  Current directory: /home/alberto.ferreira/code/external/next/
 <INFO> [08:59:45] next port.lisp (run-program port) -
  Platform port path: /home/alberto.ferreira/code/external/next/ports/gtk-webkit/next-gtk-webkit
 <INFO> [08:59:45] next port.lisp (run-program port) -
  Platform port arguments: (--port 8082 --core-socket
                            http://localhost:8081/RPC2)
 <INFO> [08:59:45] next port.lisp (run-program port) -
  Platform port log file: /home/alberto.ferreira/.local/share/next/next-gtk-webkit.log
 <INFO> [08:59:45] next base.lisp (initialize-port remote-interface fun18) -
  Polling platform port '(HOST localhost PORT 8082)'...

 <INFO> [08:59:45] next base.lisp (initialize-port remote-interface fun18) -
  Polling platform port '(HOST localhost PORT 8082)'...

 <INFO> [08:59:45] next base.lisp (initialize-port remote-interface fun18) -
  Polling platform port '(HOST localhost PORT 8082)'...

debugger invoked on a SQLITE:SQLITE-ERROR in thread
#<THREAD "main thread" RUNNING {10006A05B3}>:
  Could not prepare an sqlite statement.
Code ERROR: near "on": syntax error.
Database: /home/alberto.ferreira/.local/share/next/history.db
SQL: insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

(SQLITE:SQLITE-ERROR :ERROR "Could not prepare an sqlite statement." :STATEMENT NIL :DB-HANDLE #<SQLITE:SQLITE-HANDLE {1005D0EB43}> :SQL-TEXT "insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1")
   source: (ERROR
            (IF (EQ ERROR-CODE :CONSTRAINT)
                'SQLITE-CONSTRAINT-ERROR
                'SQLITE-ERROR)
            :FORMAT-CONTROL
            (IF (LISTP MESSAGE)
                (FIRST MESSAGE)
                MESSAGE)
            :FORMAT-ARGUMENTS
            (IF (LISTP MESSAGE)
                (REST MESSAGE))
            :DB-HANDLE DB-HANDLE :ERROR-CODE ERROR-CODE :ERROR-MSG
            (IF (AND DB-HANDLE ERROR-CODE)
                (SQLITE-FFI:SQLITE3-ERRMSG (HANDLE DB-HANDLE)))
            ...)
0] 
`

Any ideas?
Thanks

**Comment by Ambrevar** [comment]
Thanks for the feedback!
(Please next time make sure to send a textual copy of the output instead of a screenshot :p)

I'm not sure why you'd get an SQL syntax error.  Maybe a corrupt history.db?
@jmercouris @FrozenPigs any idea?

**Comment by AlbertoEAF** [comment]
Hello Ambrevar :)
This is a fresh install, first I ever done of next, don't see how I could have corrupted the history.db without using it right?
I just revised my report to provide what you asked for.
Thanks!

**Comment by Ambrevar** [comment]
Can you report

- your OS and version,
- the output of `sqlite3 --version` in a shell

?

**Comment by AlbertoEAF** [comment]
Sure, I'm using an ubntu 18.04 (64 bit) with sqlite3 (3.26.0):

> (base) [2000]alberto.ferreira:/home/alberto.ferreira$ uname -a
Linux Laptop-1107 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
(base) [2001]alberto.ferreira:/home/alberto.ferreira$ sqlite3 --version
3.26.0 2018-12-01 12:34:55 bf8c1b2b7a5960c282e543b9c293686dccff272512d08865f4600fb58238b4f9

**Comment by AlbertoEAF** [comment]
Anything else I can help? How can I launch next from SLIME so I can help debug this?

I was connecting to sqlite3 manually and trying to issue the same SQL command that fails in next with a syntax error near "on" (look closely at the bug report) and got this inside sqlite3:

`sqlite> select * from typed;
id|url|visits
1|about:blank|1
sqlite> insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1;
Error: NOT NULL constraint failed: typed.url
`

**Comment by jmercouris** [comment]
Well, the error seems quite clear, it's trying to set a value of nil for the URL, when the URL is a required column within the sqlite database.

This must be happening within `history-typed-add` based on the signature of the SQL. Therefore, I believe, somewhere in the code, something is calling `history-typed-add` with a URL of nil.

An easy fix would be to wrap everything in a `(when url ...)`, however I would like to know when a typed URL of nil is trying to be added.

**Comment by Ambrevar** [comment]
Indeed.  @AlbertoEAF how are you invoking Next?

**Comment by AlbertoEAF** [comment]
I did only this steps:
1. Clone from github
2. Change Makefile's prefix to ~/.local <- so I can avoid make install with sudo
3. Simply run 'next' in the command line <- it is found automatically in $PATH
That's when I get that error.

**Comment by AlEmerich** [comment]
Hi everyone,

Just to let you know I have the exact same error, on Ubuntu 18 and sqlite 3.22.

I builded next in ~/tools/ , add the lisp code snippet in ~/.config/next/init.lisp and try to ./tools/next/next from $HOME

**Comment by llelf** [comment]
You need newer `sqlite`

**Comment by alexanderbarbosa** [comment]
@llelf 
sqlite 3.26 release date: 12/03/18

**Comment by AlEmerich** [comment]
@llelf Ok, thanks. I just installed sqlite 3.28 (built from [Sqlite](http://www.linuxfromscratch.org/blfs/view/svn/server/sqlite.html) but the issue remains

**Comment by llelf** [comment]
```
SQLite version 3.19.3 2017-06-27 16:48:08
sqlite> insert into a (url, visits) values (0, 1) on conflict (url) do update SET visits=0;
Error: near "on": syntax error
```
vs
```
SQLite version 3.27.2 2019-02-25 16:06:06
sqlite> insert into a (url, visits) values (0, 1) on conflict (url) do update SET visits=2;
sqlite> 
```

**Comment by AlEmerich** [comment]
The error remains with the version `3.27` as well.
It is working in command line like you suggest (version `3.28` worked on a command line as well, by the way), but not from `next`

**Comment by alexanderbarbosa** [comment]
@llelf 
Oh, you meant @AlEmerich instead op! :+1:

**Comment by Ambrevar** [comment]
You need to rebuild Next against the newer SQLite.
Make sure to delete `~/.cache/common-lisp` before.

**Comment by AlEmerich** [comment]
@Ambrevar Good, that did the trick ! 

Do you guys know why it doesn't work with the latest stable release of Sqlite (3.22) ? Some syntax changed from 22 to 27 ?

**Comment by waynee95** [comment]
I ran into the same problem. I am also on Ubuntu 18.04 with sqlite3 3.29 build from source. I think I am missing something, since I still get the same error. Is there something else I need to do besides running `make all` and `./next`? I removed `~/.cache/common-lisp` and also tried to do it on a fresh clone of the project.

**Comment by Ambrevar** [comment]
@waynee95 Weird.  Can you retry and make sure the proper sqlite version is being used?
@vindarel Any idea?

**Comment by vindarel** [comment]
Same problem for me, SBCL 1.4.5 Debian, sqlite 3.22, after a rebase from master of ±1month, I have to investigate.

**Comment by waynee95** [comment]
@Ambrevar 
Sure! How exactly can I test that? 

I don't know if that helps, but I tried to find the first commit that does not work for me. 
`8d618216cf7d49d02f267d7134695e31bd68ceb4` is the last commit that works for me.

**Comment by Ambrevar** [comment]
Yes, that was to be expected, the subsequent commit by @FrozenPigs is
the one that changes the SQL query which causes the error.

**Comment by jmercouris** [comment]
I have fixed this in the latest source with commit bae50c8. I will leave this open until a new packaged release is made/the fix is verified.

**Comment by vindarel** [comment]
I rebased and ran `(next:start-with-port)`, and I still get

```
Could not prepare an sqlite statement.
Code ERROR: near "on": syntax error.
Database: /home/vince/.local/share/next/history.db

…

  0: (SQLITE:SQLITE-ERROR :ERROR "Could not prepare an sqlite statement." :STATEMENT NIL :DB-HANDLE #<SQLITE:SQLITE-HANDLE {10031899F3}> :SQL-TEXT "insert into typed (url, visits) values (?, 1) on conflict..
  1: ((:METHOD INITIALIZE-INSTANCE :AFTER (SQLITE:SQLITE-STATEMENT)) #<SQLITE:SQLITE-STATEMENT {100318A3E3}>) [fast-method]
  2: ((LAMBDA (SB-PCL::|.P0.| SB-PCL::|.P1.|)) #<unavailable argument> #<unavailable argument>)
  3: (SQLITE:PREPARE-STATEMENT #<SQLITE:SQLITE-HANDLE {10031899F3}> "insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1")
      Locals:
        DB = #<SQLITE:SQLITE-HANDLE {10031899F3}>
        SQL = "insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1"
  4: (SQLITE:EXECUTE-NON-QUERY #<SQLITE:SQLITE-HANDLE {10031899F3}> "insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1" "https://next.atlas.engineer/st..
      Locals:
        DB = #<SQLITE:SQLITE-HANDLE {10031899F3}>
        PARAMETERS = ("https://next.atlas.engineer/start")
        SQL = "insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1"
  5: (SQLITE:EXECUTE-NON-QUERY #<SQLITE:SQLITE-HANDLE {10031899F3}> "insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1" "https://next.atlas.engineer/st..
      Locals:
        SB-DEBUG::ARG-0 = #<SQLITE:SQLITE-HANDLE {10031899F3}>
        SB-DEBUG::ARG-1 = "insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1"
        SB-DEBUG::MORE = ("https://next.atlas.engineer/start")
  6: (NEXT::HISTORY-TYPED-ADD "https://next.atlas.engineer/start")
      Locals:
        URL = "https://next.atlas.engineer/start"
  7: ((:METHOD NEXT::SET-URL-BUFFER (T NEXT::BUFFER)) "https://next.atlas.engineer/start" #<NEXT::BUFFER {100316F303}> NIL) [fast-method]
  8: ((:METHOD NEXT::SETUP (NEXT::DOCUMENT-MODE NEXT::BUFFER)) #<NEXT::DOCUMENT-MODE {1003170673}> #<NEXT::BUFFER {100316F303}>) [fast-method]
  9: ((:METHOD NEXT::BUFFER-MAKE (NEXT::REMOTE-INTERFACE)) #<NEXT::REMOTE-INTERFACE {1002E8D9E3}> "default" NIL) [fast-method]
 10: (NEXT::MAKE-WINDOW)
 11: ((:METHOD NEXT::INITIALIZE-PORT (NEXT::REMOTE-INTERFACE)) #<NEXT::REMOTE-INTERFACE {1002E8D9E3}>) [fast-method]
 12: (NEXT:START :WITH-PLATFORM-PORT-P T)
```

this lends us to `history-typed-add`, which your commit doesn't touch (so I don't understand it).

**Comment by jmercouris** [comment]
Hi Vindarel, you are right, I only fixed part of it, there is also
history-typed. I will get to this.

Thanks for pointing it out!

**Comment by jmercouris** [comment]
That is, assuming the version of SQLite everyone has does not support the following query:

`insert into typed (url, visits) values (?, 1) on conflict (url) do update set visits = typed.visits + 1`

**Comment by vindarel** [comment]
oops, I thought of discussing this on a PR. Nonetheless, it works for me©, sqlite 3.22.

GIven this: https://sqlite.org/lang_conflict.html the "on conflict" extension to INSERT was added in 3.24. I made the query in two steps instead of a one-liner, so improvements are possible.

**Comment by Aphsai** [comment]
Hi, I'm still getting the same error :(

```(SQLITE:SQLITE-ERROR :ERROR "Could not prepare an sqlite statement." :STATEMENT NIL
:DB-HANDLE #<SQLITE:SQLITE-HANDLE {1004DF4D53}> :SQL-TEXT "select visits from typed
where url like ? limit 1;")
   source: (ERROR
            (IF (EQ ERROR-CODE :CONSTRAINT)
                'SQLITE-CONSTRAINT-ERROR
                'SQLITE-ERROR)
            :FORMAT-CONTROL
            (IF (LISTP MESSAGE)
                (FIRST MESSAGE)
                MESSAGE)
            :FORMAT-ARGUMENTS
            (IF (LISTP MESSAGE)
                (REST MESSAGE))
            :DB-HANDLE DB-HANDLE :ERROR-CODE ERROR-CODE :ERROR-MSG
            (IF (AND DB-HANDLE ERROR-CODE)
                (SQLITE-FFI:SQLITE3-ERRMSG (HANDLE DB-HANDLE)))
            ...)
```

I'm not sure it'll help but this came up as I was installing:
```WARNING:
   bare references to struct types are deprecated. Please use (:POINTER
                                                               (:STRUCT
                                                                SQLITE3)) or (:STRUCT
                                                                              SQLITE3) instead.
WARNING:
   bare references to struct types are deprecated. Please use (:POINTER
                                                               (:STRUCT
                                                                SQLITE3-STMT)) or (:STRUCT
                                                                                   SQLITE3-STMT) instead.
``` 
Though I imagine warnings shouldn't pose too much of a problem.

My SQLite version is : 
`3.28.0 2019-04-16 19:49:53 884b4b7e502b4e991677b53971277adfaf0a04a284f8e483e2553d0f83156b50
`

**Comment by waynee95** [comment]
@Aphsai 
Did you delete `~/.cache/common-lisp` before building next?

**Comment by Aphsai** [comment]
Yup

**Comment by vindarel** [comment]
It doesn't seem the same error. I wrote the problematic sql line in the patch of this issue. It works without warnings for me.
Can you open a new issue ?
