### ISSUE TITLE
stumpwm doesn't show next

### ISSUE THREAD

**Issue by oochen** [atlas-engineer/next#239]
Thanks for the great tool. 
However when I use the next with stumpwm, it does not show properly.
The output says:
<INFO> [11:07:10] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/oo/.config/next/init.lisp...
 <WARN> [11:07:10] next base.lisp (start) -
  swank:*communication-style* is set to :SPAWN, recommended value is :fd-handler

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "Anonymous thread" RUNNING {1003FFAED3}>:
  No server addresses left to try to open.

The current thread is not at the foreground,
SB-THREAD:RELEASE-FOREGROUND has to be called in #<SB-THREAD:THREAD "main thread" RUNNING {10005D84F3}>
for this thread to enter the debugger.

I use the xterm to start next. The next works fine on unity.

**Comment by alexanderbarbosa** [comment]
I had this very error, but now its working fine.

**Comment by oochen** [comment]
indeed, the next does not seem to source the config file when it says it does.
I try to get the variable proxy-url I set, 
WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) signaled an error: The function
                                                                #<STANDARD-GENERIC-FUNCTION NEXT::HELP-MODE (1)>
                                                              requires at least 1 argument..

**Comment by Ambrevar** [comment]
Are you running Next 1.2.x or a version compiled from master?

Your first error 

> No server addresses left to try to open.

means you are running 1.2.x, while the last error


>    Method handler (NEXT::CORE-OBJECT
>                    NEXT::PUSH-INPUT-EVENT) signaled an error: The function
>                                                                 #<STANDARD-GENERIC-FUNCTION NEXT::HELP-MODE (1)>
>                                                               requires at least 1 argument..

means you are running against master.  Did you mix both?

Regarding your issue with setting proxy-url: It's broken on master, but
I'm going to fix it for good in the coming days.

**Comment by oochen** [comment]
Yes, I was running 1.2.x. compiled from the source.
Thanks.

**Comment by Ambrevar** [comment]
Which commit did you check out?
Either check out tag 1.2.2 or latest master, but it seems that the commit you chose for a check out was broken :p

**Comment by oochen** [comment]
Sorry for the delay.
I clone the latest. I will try the stable version :)

**Comment by alexanderbarbosa** [comment]
Just build next and stumpwm "shows" it.

Stumpwm: Upstream
Next: upstream

**Comment by montaropdf** [comment]
Hello,

I have a similar problem on fedora 30 with stumpwm compiled from sources and next compiled from sources.

Bellow are what  I got in the terminal
```

~ $ bin/next
 <INFO> [22:39:35] next base.lisp (start) - NEXT::+VERSION+: "1.2.2-99159da" 
 <INFO> [22:39:35] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/roland/.config/next/init.lisp...
 <WARN> [22:39:35] next minibuffer.lisp (echo) -
  Can't echo (~a enabled. MINIBUFFER-MODE) without minibuffer or interface

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "Anonymous thread" RUNNING {1004E2BC33}>:
  No more mechanisms to try.

debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT in thread
#<THREAD "main thread" RUNNING {10006405B3}>:
  Interactive interrupt at #x7F56D5364FAB.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

("bogus stack frame")
0] 0
~ $ 
```

**Comment by Ambrevar** [comment]
How do you start stumpwm?

Do you have a D-Bus session bus running?

Also make sure there is no left-over process or Next that's running
(both "next" and "next-gtk-webkit").  Then try again.

**Comment by alexanderbarbosa** [comment]
`pkill next`, should kill everything!

**Comment by montaropdf** [comment]
Hello,

I have a similar problem on fedora 30 with stumpwm compiled from sources and next compiled from sources.

Bellow are what  I got in the terminal
```

~ $ bin/next
 <INFO> [22:39:35] next base.lisp (start) - NEXT::+VERSION+: "1.2.2-99159da" 
 <INFO> [22:39:35] next base.lisp (load-lisp-file form-fun-4) -
  Loading configuration from /home/roland/.config/next/init.lisp...
 <WARN> [22:39:35] next minibuffer.lisp (echo) -
  Can't echo (~a enabled. MINIBUFFER-MODE) without minibuffer or interface

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "Anonymous thread" RUNNING {1004E2BC33}>:
  No more mechanisms to try.

debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT in thread
#<THREAD "main thread" RUNNING {10006405B3}>:
  Interactive interrupt at #x7F56D5364FAB.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

("bogus stack frame")
0] 0
~ $ 
```

> How do you start stumpwm? Do you have a D-Bus session bus running? Also make sure there is no left-over process or Next that's running (both "next" and "next-gtk-webkit"). Then try again.

Hi,

- I start stumpwm from the login manager. I have create a desktop file in /usr/share/xsessions with the following content:

```
[Desktop Entry]
Name=stumpwm
Comment=Common Lisp based Tiling window manager
Exec=stumpwm
TryExec=stumpwm
Type=Application
X-LightDM-DesktopName=stumpwm
DesktopNames=stumpwm
Keywords=tiling;wm;windowmanager;window;manager;
```

- You will, also, find attached the Makefile I used to compile Next.
[Makefile.txt](https://github.com/atlas-engineer/next/files/3331461/Makefile.txt)

- I made sure that no Next process were running.

- I don't know if it could make a difference, but I have also GNOME on Wayland installed, could there be a possibility that some dependencies relies on wayland while others use X?

Any way, I will try 2 things.
1. Run my compiled version of Next with GNOME, to see If Next is working with that environment
2. Run the pre-compiled version of Next under stumpwm.

**Comment by montaropdf** [comment]
Hello again,

1. The pre-compiled version of next is working (I am using it to write this comment)
2. My compiled version of Next don't work with GNOME be it in Wayland or X.org, so my problem seems different.

@oochen, did you try with another WM?

**Comment by Ambrevar** [comment]
What is the pre-compiled version of Next?  Do you mean the 1.2.2 Guix
pack?
If so, it does not use D-Bus, so that might explain the difference.

As far as I know, GNOME relies on D-Bus, so it should be started when
you log in.
Can you make sure that


    ps -U $USER | grep dbus-daemon

returns something?

**Comment by montaropdf** [comment]
@Ambrevar , yes, version 1.2.2 Guix pack

On my system, the message bus daemon is  composed of dbus-broker and dbus-broker-launch, according to the man page it is another implementation of the message bus protocol.

**Comment by Ambrevar** [comment]
What is your system?
Never heard of dbus-broker, this could be a problem indeed.
Can you install regular D-Bus?

**Comment by montaropdf** [comment]
> What is your system? Never heard of dbus-broker, this could be a problem indeed. Can you install regular D-Bus?

I use Fedora 30

dbus-daemon is there with a service in systemd. Unfortunally, if I start it, it stop with an error. I suppose it is due to the presence of dbus-broker.

I will try to find a way to replace dbus-broker with dbus-daemon.

I will keep you informed.

**Comment by bradjcheme** [comment]
I'm on Fedora 30, too, and am encountering the same issues with a fresh pull from the master branch, Next 1.2.2-07dcaf5. I'm using i3wm, in lieu of stumpwm, and my session is started from gnome's login manager.

**Comment by ak-coram** [comment]
I have the same issue on FreeBSD

**Comment by Ambrevar** [comment]
Which window manager and login manager are you using?

Do you have a dbus _user session_ running?  If not, try

  $ export $(dbus-launch) && next

**Comment by ak-coram** [comment]
I'm also using stumpwm. After running `export $(dbus-launch)` I get a different error (previously it was `No server addresses left to try to open.`):

```
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1005442D23}>:
  No more mechanisms to try.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005442D23}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No more mechanisms to try." {100621F143}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No more mechanisms to try." {100621F143}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No more mechanisms to try." {100621F143}>)
3: (ERROR "No more mechanisms to try.")
4: ((:METHOD DBUS/PROTOCOLS:AUTHENTICATE (T DBUS/CONNECTIONS:STANDARD-CONNECTION)) (#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {10062179E3}>) #<DBUS/TRANSPORT-UNIX:UNIX-CONNECTION {1006148FE3}> :IF-FAILED #<unused argument>) [fast-method]
5: ((LAMBDA NIL :IN DBUS/PROTOCOLS:AUTHENTICATE))
6: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1005A7D3DB}> #<event base, 0 FDs monitored, using: #<kqueue(2) multiplexer> {100553FCC3}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1005698F83}>))
7: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
13: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {801AD7E3B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005442D23}>> NIL T NIL)
14: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005442D23}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1005442CCB}> NIL)
15: ("foreign function: call_into_lisp")
16: ("foreign function: new_thread_trampoline")
17: ("foreign function: pthread_create")
```

**Comment by alexanderbarbosa** [comment]
@ak-coram 

`No server addresses left to try to open`: either set next to use another port or whatever using it to a different one. 

Might be Next early server that did not die, screen/tmux.

**Comment by ak-coram** [comment]
@alexanderbarbosa: thank you for your suggestions.

I've looked into it a bit more: looks like the external auth request to the session dbus gets rejected. I'm not really sure why, since that's all it says. Any ideas?

**Comment by Ambrevar** [comment]
I've tried Next with Stumpwm: I got no issue in particular.  I don't think StumpWM has anything to do with dbus.

I've just pushed a fix which should start a user dbus-daemon automatically if the communication fails with the default dbus-daemon:
c420d77bbbf1f3b228650d01b87c383f954b3385.

@ak-coram @montaropdf @bradjcheme @oochen Is it working for you now on master?

**Comment by ak-coram** [comment]
@Ambrevar: thanks for your changes. Sadly I still get the same error on FreeBSD:

```
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {100543BB93}>:
  No server addresses left to try to open.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100543BB93}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No server addresses left to try to open." {10062F0153}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No server addresses left to try to open." {10062F0153}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No server addresses left to try to open." {10062F0153}>)
3: (ERROR "No server addresses left to try to open.")
4: ((LAMBDA NIL :IN DBUS/PROTOCOLS:OPEN-CONNECTION))
5: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1005A7507B}> #<event base, 0 FDs monitored, using: #<kqueue(2) multiplexer> {1005537CC3}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1005690F83}>))
6: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
7: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
12: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {801AD7E3B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100543BB93}>> NIL T NIL)
13: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100543BB93}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100543BB3B}> NIL)
14: ("foreign function: call_into_lisp")
15: ("foreign function: new_thread_trampoline")
16: ("foreign function: pthread_create")
```

When I run `export $(dbus-launch)` before starting next, I get the following:

```
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {100543BB93}>:
  No more mechanisms to try.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100543BB93}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No more mechanisms to try." {1006217143}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No more mechanisms to try." {1006217143}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No more mechanisms to try." {1006217143}>)
3: (ERROR "No more mechanisms to try.")
4: ((:METHOD DBUS/PROTOCOLS:AUTHENTICATE (T DBUS/CONNECTIONS:STANDARD-CONNECTION)) (#<DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM {100620F9E3}>) #<DBUS/TRANSPORT-UNIX:UNIX-CONNECTION {1006141003}> :IF-FAILED #<unused argument>) [fast-method]
5: ((LAMBDA NIL :IN DBUS/PROTOCOLS:AUTHENTICATE))
6: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1005A753DB}> #<event base, 0 FDs monitored, using: #<kqueue(2) multiplexer> {1005537CC3}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1005690F83}>))
7: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
11: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
13: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {801AD7E3B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100543BB93}>> NIL T NIL)
14: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100543BB93}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100543BB3B}> NIL)
15: ("foreign function: call_into_lisp")
16: ("foreign function: new_thread_trampoline")
17: ("foreign function: pthread_create")
```

As I mentioned the second one seems to be an issue with dbus auth.

**Comment by Ambrevar** [comment]
To clarify: Are you running StumpWM?  Can you try to reproduce in a
different WM?

I'll see if I can expose more D-Bus messages to see what's going on.

**Comment by ak-coram** [comment]
Yes, I'm running StumpWM. I'll try to reproduce with another WM and get back to you.

In the second error you can see that the only auth mechanism available is `DBUS/AUTH-DBUS-EXTERNAL:DBUS-EXTERNAL-AUTHENTICATION-MECHANISM`. I've looked at the raw auth response from dbus and it's `REJECTED EXTERNAL`.

**Comment by Ambrevar** [comment]
Master does not use D-Bus anymore (we've switched to FFI) so this issue should be fixed altogether.
Feel free to reopen if you experience more troubles.
