### ISSUE TITLE
Unable to kill buffers

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#310]
Hi,

Asking Next to kill current page issues:

``` lisp
   Method handler  (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) 

signaled an error: The value
NIL
is not of type
(AND
 ALEXANDRIA.1.0.0:PROPER-SEQUENCE
 (NOT
  (SATISFIES
   ALEXANDRIA.1.0.0:EMPTYP))).
```

Thanks! 

---
Debian 10 SID
Next: Upstream

**Comment by Ambrevar** [comment]
I can't reproduce.
Which commit are you running?
Can you share a recipe?

**Comment by alexanderbarbosa** [comment]
@Ambrevar 

Next 1.3.0-1628b90

Opening github.com, reddit.com and cnn.com, I can kill one of three buffers but unable to kill the others.

And still issuing: 

```WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) signaled an error: The value
                                                                NIL
                                                              is not of type
                                                                (AND
                                                                 ALEXANDRIA.1.0.0:PROPER-SEQUENCE
                                                                 (NOT
                                                                  (SATISFIES
                                                                   ALEXANDRIA.1.0.0:EMPTYP))).
WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::PUSH-INPUT-EVENT) signaled an error: The value
                                                                NIL
                                                              is not of type
                                                                (AND
                                                                 ALEXANDRIA.1.0.0:PROPER-SEQUENCE
                                                                 (NOT
                                                                  (SATISFIES
                                                                   ALEXANDRIA.1.0.0:EMPTYP))).
```

**Comment by alexanderbarbosa** [comment]
weird, running next with REPL as expected kill all buffers.

**Comment by Ambrevar** [comment]
Did you `make` everything after your last checkout?

**Comment by alexanderbarbosa** [comment]
@Ambrevar 

Can't say why, just compiled it again and the issue is fixed. 

I just update SBCL, from master, might be why.

**Comment by Ambrevar** [comment]
Either you forgot to `make` or your fasl cache (in ~/.cache/common-lisp)
was out of sync.  Happens with macros.

**Comment by jmercouris** [comment]
Happens to all of us :D no worries! I remember in the good old days I used to make a habit of cleaning every single project in eclipse before recompiling... so many times it was part of the magical incantation to make things work :)

**Comment by alexanderbarbosa** [comment]
makes sense!
