### ISSUE TITLE
There are several error

### ISSUE THREAD

**Issue by SXGNH** [atlas-engineer/next#51]
cl-webkit/dom/init.lisp  load **libwebkit2gtk-3.0.so** failed, it should is **libwebkit2gtk-4.0.so** 

```
(define-foreign-library libwebkit2
    (:unix (:or "libwebkit2gtk-3.0.so")))
----------------------------------------------
(define-foreign-library libwebkit2
    (:unix (:or  "libwebkit2gtk-4.0.so"
                 "libwebkit2gtk-3.0.so")))
```
arch: 
1. C-x c quit cause crash,and some other unknown is action also cause crash.terminal have not 
             any info backfeed.
2.  link-hint invalid ,when input link-hint tip character and return jump page it no any action 
     mouse clicked also no any action but there are little some link is can jump .
3.  terminal info : 
`gtk-critical **: gtk-tree-path-to-string: assertion 'result !=NULL' failed.  `

debian:  
when execute **(next:start)** appear gui directly crash. ui death
terminal info : 
```
glib-gobject-warning **: cannot register existing type 'webkitwebcontext'
glib-gobject-critical **: g_once_init_leave: assertion 'result !=0 ' failed.
glib-gobject-critical **: g_object_new: assertion 'g_type_is_object (object_tyhpe)' failed.
```
---------------------------------------------------
 invalid directory :home, when execute **(asdf:load-asd "full-path-name")**  don't use "~/../../.." , need to use full path name.

**Comment by jmercouris** [comment]
Hi, I believe I have fixed these issues, can you please try again? Thank you!

**Comment by SXGNH** [comment]
@jmercouris 
arch and debian now already have not large error, 
but C-x C-c quit still crash ,but me uncertain it is ui no response or program crash .

link-hint work very good , there are some links cannot tips. for example: when have not log in [github.com](url) ,top left corner  logo on main page  not show link-hint.

BSD and Fedora cannot run ,BSD UI have not show content but also have not death and crash,just like only a gtk frame.
fedora UI show **could not connect: network is unreachable** but firefox is normal used

If can give nEXT append a page load progress bar, just like safari and firefox like that should is very nice.

Can append show page title in down drop list of input bar?

Can support emacs edit mode in input bar ?

**Comment by Ambrevar** [comment]
@SXGNH @jmercouris This should now be fixed on master, right?
